matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      language: c
      sudo: required
      env:
        - DISTRO=trusty

    - os: linux
      language: c
      sudo: required
      env:
        - DISTRO=precise

language: c

before_install:
  - sudo mv /etc/apt/sources.list.d/pgdg* /tmp
  - sudo apt-get purge -y libgdal* libgeos* libspatialite*
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install cmake libspatialite-dev libfcgi-dev libproj-dev libgeos-dev libgdal-dev libtiff-dev libgeotiff-dev apache2-dev libpcre3-dev libsqlite3-dev libdb-dev
# For testing
  - sudo apt-get install libxml2-utils apache2 gdal-bin

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DWITH_TIFF=ON -DWITH_GEOTIFF=ON -DWITH_TIFF_WRITE_SUPPORT=ON -DWITH_PCRE=ON -DWITH_SQLITE=ON -DWITH_BERKELEY_DB=ON
  - make -j3
  - sudo make install
# Only test with Apache 2.4
  - if test "$DISTRO" = "trusty"; then cd ../tests; sh ./travis_setup.sh; sh ./run_tests.sh; fi


#notifications:
#  email:
#    recipients:
#      - thomas.bonfort@gmail.com
#  irc:
#    channels:
#      - "irc.freenode.org#mapserver"
#    use_notice: true

