image: Visual Studio 2019

platform:
- x64

environment:
  matrix:
  - VS_VERSION: Visual Studio 16 2019

shallow_clone: true

build_script:
  - echo build_script
  - set "BUILD_FOLDER=%APPVEYOR_BUILD_FOLDER:\=/%"
  - if "%platform%" == "x64" SET VS_FULL=%VS_VERSION%
  - if "%platform%" == "x64" SET VS_ARCH=x64
  - if "%platform%" == "x86" SET VS_FULL=%VS_VERSION%
  - if "%platform%" == "x86" SET VS_ARCH=Win32 
  - if "%platform%" == "x86" SET SDK=release-1928
  - if "%platform%" == "x64" SET SDK=release-1928-x64
  - if "%platform%" == "x64" call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build/vcvars64.bat"
  - if "%platform%" == "x86" call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build/vcvars32.bat"
  - echo "%VS_FULL%"
  - set SDK_ZIP=%SDK%-dev.zip
  - set SDK_URL=http://download.gisinternals.com/sdk/downloads/%SDK_ZIP%
  - echo "%SDK_ZIP%"
  - echo "%SDK_URL%"
  - mkdir sdk
  - cd sdk
  - appveyor DownloadFile "%SDK_URL%"
  - 7z x "%SDK_ZIP%" > nul
  - cd %SDK%
  #- cd lib
  #- copy libpng.lib libpng.lib.lib
  - cd %APPVEYOR_BUILD_FOLDER%
  - set SDK_PREFIX=%BUILD_FOLDER%/sdk/%SDK%
  - set SDK_INC=%BUILD_FOLDER%/sdk/%SDK%/include
  - set SDK_LIB=%BUILD_FOLDER%/sdk/%SDK%/lib
  - set SDK_BIN=%BUILD_FOLDER%/sdk/%SDK%/bin
  - set REGEX_DIR=%BUILD_FOLDER%/sdk/support/regex-0.12

  - if not exist apr-1.6.3-win32-src.zip appveyor DownloadFile https://archive.apache.org/dist/apr/apr-1.6.3-win32-src.zip
  - 7z x apr-1.6.3-win32-src.zip
  - mkdir build-cmake
  - cd build-cmake
  - mkdir apr
  - cd apr
  - cmake -G "NMake Makefiles" 
        -DCMAKE_INSTALL_PREFIX=%SDK_PREFIX% 
        -DCMAKE_BUILD_TYPE=RelWithDebInfo 
        -DMIN_WINDOWS_VER=0x0600 
        -DAPR_HAVE_IPV6=ON 
        -DAPR_INSTALL_PRIVATE_H=ON 
        -DAPR_BUILD_TESTAPR=OFF 
        -DAPU_HAVE_ODBC=OFF 
        -DINSTALL_PDB=OFF ..\..\apr-1.6.3
  - nmake
  - nmake install

  - cd %APPVEYOR_BUILD_FOLDER%

  - if not exist apr-util-1.6.1-win32-src.zip appveyor DownloadFile https://archive.apache.org/dist/apr/apr-util-1.6.1-win32-src.zip
  - 7z x apr-util-1.6.1-win32-src.zip
  - mkdir build-cmake\apr-util
  - cd build-cmake\apr-util
  - cmake -G "NMake Makefiles" 
        -DCMAKE_INSTALL_PREFIX=%SDK_PREFIX% 
        -DOPENSSL_ROOT_DIR=%SDK_PREFIX% 
        -DCMAKE_BUILD_TYPE=RelWithDebInfo 
        -DAPU_HAVE_CRYPTO=ON 
        -DAPU_HAVE_ODBC=OFF 
        -DAPR_HAS_LDAP=OFF 
        -DAPR_BUILD_TESTAPR=OFF 
        -DINSTALL_PDB=OFF ..\..\apr-util-1.6.1
  - nmake
  - nmake install

  - cd %APPVEYOR_BUILD_FOLDER%

  - set PCRE_VERSION=8.38
  - set PCRE=pcre-%PCRE_VERSION%
  - if not exist %PCRE%.zip appveyor DownloadFile "http://zoo-project.org/dl/%PCRE%.zip"
  - 7z x %PCRE%.zip > nul
  - mkdir build-cmake\pcre
  - cd build-cmake\pcre
  - cmake -G "NMake Makefiles" 
        -DCMAKE_INSTALL_PREFIX=%SDK_PREFIX% 
        -DCMAKE_BUILD_TYPE=RelWithDebInfo 
        -DBUILD_SHARED_LIBS=ON 
        -DPCRE_BUILD_TESTS=OFF 
        -DPCRE_BUILD_PCRECPP=OFF 
        -DPCRE_BUILD_PCREGREP=OFF 
        -DPCRE_SUPPORT_PCREGREP_JIT=OFF 
        -DPCRE_SUPPORT_UTF=ON 
        -DPCRE_SUPPORT_UNICODE_PROPERTIES=ON 
        -DPCRE_NEWLINE=CRLF 
        -DINSTALL_MSVC_PDB=OFF ..\..\%PCRE%
  - nmake
  - nmake install

  - echo %SDK_LIB%
  - cd %SDK_LIB%
  - dir
  - copy "%SDK_LIB%/libfcgi.lib" "%SDK_LIB%/fcgi.lib" /Y
  - copy "%SDK_LIB%/apr-1.lib" "%SDK_LIB%/apr-1-1.lib" /Y
  - copy "%SDK_LIB%/libapr-1.lib" "%SDK_LIB%/apr-1.lib" /Y > nul
  - copy "%SDK_LIB%/aprutil-1.lib" "%SDK_LIB%/aprutil-1-1.lib" /Y > nul
  - copy "%SDK_LIB%/libaprutil-1.lib" "%SDK_LIB%/aprutil-1.lib" /Y > nul
  - xcopy "%REGEX_DIR%/*.h" "%SDK_INC%" /O /X /E /H /K /Y > nul

  - cd %APPVEYOR_BUILD_FOLDER%

  - mkdir build
  - cd build
  - cmake -G "%VS_FULL%" -A %VS_ARCH% 
        -DWITH_APACHE=OFF 
        -DWITH_FCGI=ON 
        -DWITH_PCRE=ON 
        -DWITH_TIFF=OFF 
        -DCMAKE_PREFIX_PATH=%SDK_PREFIX% ..
  - cmake --build . --config Release

  - copy "%SDK_LIB%\apr-1-1.lib" "%SDK_LIB%\apr-1.lib" /Y > nul
  - copy "%SDK_LIB%\aprutil-1-1.lib" "%SDK_LIB%\aprutil-1.lib" /Y > nul
  - copy "%SDK_BIN%\libapr-1.dll" "%SDK_BIN%\apr-1.dll" /Y > nul
  - copy "%SDK_BIN%\libaprutil-1.dll" "%SDK_BIN%\aprutil-1.dll" /Y > nul
  - copy "%SDK_BIN%\libfcgi.dll" "%SDK_BIN%\fcgi.dll" /Y > nul
  - copy "Release\*dll" "%SDK_BIN%" /Y > nul
  - copy "Release\*lib" "%SDK_LIB%" /Y > nul
  - copy "cgi\Release\*exe" "%SDK_BIN%" /Y > nul
  - copy "util\Release\*exe" "%SDK_BIN%" /Y > nul

after_build:
  - cd %SDK_BIN%
  - 7z a %APPVEYOR_BUILD_FOLDER%\mapcache.zip libapr*.dll apr*.dll pcre.dll pcreposix.dll mapcache.dll 
        mapcache.fcgi.exe mapcache_seed.exe %APPVEYOR_BUILD_FOLDER%\mapcache.xml

test_script:
  - cd %SDK_BIN%
  - set MAPCACHE_CONFIG_FILE=mapcache.xml
  - set PATH_INFO="/"
  - set REQUEST_METHOD=GET
  - set QUERY_STRING="SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&FORMAT=image/png&SRS=EPSG:4326&BBOX=0,0,10,10&WIDTH=256&HEIGHT=256&LAYERS=test&TRANSPARENT=TRUE"
  - rem mapcache.fcgi.exe
  - rem mapcache_seed.exe

deploy: off

artifacts:
  - path: mapcache.zip
    name: mapcache
    type: zip
